export const revenueTimeline = [
    { month: 'Oct', amount: 8200, invoices: 18 },
    { month: 'Nov', amount: 9100, invoices: 21 },
    { month: 'Dec', amount: 10400, invoices: 24 },
    { month: 'Jan', amount: 11850, invoices: 27 },
    { month: 'Feb', amount: 12480, invoices: 29 },
    { month: 'Mar', amount: 13240, invoices: 31 },
];
export const initialAdminProfile = {
    firstName: 'Areeb',
    lastName: 'Khan',
    role: 'CKAM Administrator',
    roleAr: 'CKAM Administrator',
    email: 'admin@ckam.com',
    phone: '+973 3900 5544',
    location: 'Manama, Bahrain',
    locationAr: 'Manama, Bahrain',
    website: 'ckam.cyphersol.com',
    bio: {
        en: 'Responsible for photographer approvals, subscription operations, bilingual website management, and onboarding workflows.',
        ar: 'Responsible for photographer approvals, subscription operations, bilingual website management, and onboarding workflows.',
    },
    avatar: '',
    twoFactorEnabled: false,
    twoFactorMethod: 'email',
    twoFactorEmail: 'admin@ckam.com',
    twoFactorPhone: '+973 3900 5544',
};
export const initialPhotographers = [
    {
        id: 'p-101',
        name: 'Ava Lens',
        city: 'Austin, TX',
        specialty: 'Weddings',
        planId: 'studio-pro',
        planName: { en: 'Studio Pro', ar: 'Studio Pro' },
        accountStatus: 'active',
        subscriptionStatus: 'active',
        tapStatus: 'connected',
        monthlyRevenue: 349,
        joinedOn: '2026-01-14',
        email: 'ava@ckamstudio.com',
        phone: '+1 (555) 301-2014',
        publicUrl: 'ckam.io/ava-lens',
        businessName: 'Ava Lens Studio',
        about: {
            en: 'Wedding photographer focused on destination events, premium albums, and smooth client communication.',
            ar: 'Wedding photographer focused on destination events, premium albums, and smooth client communication.',
        },
        preferredLanguage: 'English',
        preferredLanguageAr: 'English',
        preferredCurrency: 'USD',
        totalClients: 42,
        upcomingBookings: 6,
        experience: '8 years',
        experienceAr: '8 years',
        kycSubmitted: true,
    },
    {
        id: 'p-102',
        name: 'Malik Porter',
        city: 'Chicago, IL',
        specialty: 'Portraits',
        planId: 'starter',
        planName: { en: 'Starter', ar: 'Starter' },
        accountStatus: 'waiting',
        subscriptionStatus: 'trial',
        tapStatus: 'pending',
        monthlyRevenue: 39,
        joinedOn: '2026-03-02',
        email: 'malik@portraitlane.co',
        phone: '+1 (555) 615-4402',
        publicUrl: 'ckam.io/malik-porter',
        businessName: 'Portrait Lane',
        about: {
            en: 'Portrait specialist building a studio-focused booking system with bilingual landing pages.',
            ar: 'Portrait specialist building a studio-focused booking system with bilingual landing pages.',
        },
        preferredLanguage: 'English',
        preferredLanguageAr: 'English',
        preferredCurrency: 'USD',
        totalClients: 9,
        upcomingBookings: 2,
        experience: '3 years',
        experienceAr: '3 years',
        kycSubmitted: true,
    },
    {
        id: 'p-103',
        name: 'Sienna Hart',
        city: 'Miami, FL',
        specialty: 'Lifestyle',
        planId: 'growth',
        planName: { en: 'Growth', ar: 'Growth' },
        accountStatus: 'active',
        subscriptionStatus: 'active',
        tapStatus: 'connected',
        monthlyRevenue: 129,
        joinedOn: '2025-11-18',
        email: 'sienna@hartvisuals.com',
        phone: '+1 (555) 448-1904',
        publicUrl: 'ckam.io/sienna-hart',
        businessName: 'Hart Visuals',
        about: {
            en: 'Lifestyle creator serving brands and families with polished galleries and recurring mini sessions.',
            ar: 'Lifestyle creator serving brands and families with polished galleries and recurring mini sessions.',
        },
        preferredLanguage: 'Arabic',
        preferredLanguageAr: 'Arabic',
        preferredCurrency: 'SAR',
        totalClients: 27,
        upcomingBookings: 4,
        experience: '5 years',
        experienceAr: '5 years',
        kycSubmitted: true,
    },
    {
        id: 'p-104',
        name: 'Daniel Knox',
        city: 'Seattle, WA',
        specialty: 'Commercial',
        planId: 'studio-pro',
        planName: { en: 'Studio Pro', ar: 'Studio Pro' },
        accountStatus: 'deactivated',
        subscriptionStatus: 'inactive',
        tapStatus: 'not-started',
        monthlyRevenue: 0,
        joinedOn: '2025-08-22',
        email: 'daniel@knoxframes.com',
        phone: '+1 (555) 990-4401',
        publicUrl: 'ckam.io/daniel-knox',
        businessName: 'Knox Frames',
        about: {
            en: 'Commercial photographer managing product shoots and corporate retainers across multiple teams.',
            ar: 'Commercial photographer managing product shoots and corporate retainers across multiple teams.',
        },
        preferredLanguage: 'English',
        preferredLanguageAr: 'English',
        preferredCurrency: 'USD',
        totalClients: 18,
        upcomingBookings: 0,
        experience: '10 years',
        experienceAr: '10 years',
        kycSubmitted: false,
    },
    {
        id: 'p-105',
        name: 'Noor Aftab',
        city: 'New York, NY',
        specialty: 'Events',
        planId: 'growth',
        planName: { en: 'Growth', ar: 'Growth' },
        accountStatus: 'active',
        subscriptionStatus: 'active',
        tapStatus: 'pending',
        monthlyRevenue: 129,
        joinedOn: '2026-02-04',
        email: 'noor@focusline.studio',
        phone: '+1 (555) 273-1180',
        publicUrl: 'ckam.io/noor-aftab',
        businessName: 'Focusline Studio',
        about: {
            en: 'Event photographer covering conferences and branded experiences with fast turnaround needs.',
            ar: 'Event photographer covering conferences and branded experiences with fast turnaround needs.',
        },
        preferredLanguage: 'Arabic',
        preferredLanguageAr: 'Arabic',
        preferredCurrency: 'BHD',
        totalClients: 21,
        upcomingBookings: 5,
        experience: '6 years',
        experienceAr: '6 years',
        kycSubmitted: true,
    },
    {
        id: 'p-106',
        name: 'Elena Brooks',
        city: 'Denver, CO',
        specialty: 'Family',
        planId: 'starter',
        planName: { en: 'Starter', ar: 'Starter' },
        accountStatus: 'waiting',
        subscriptionStatus: 'trial',
        tapStatus: 'pending',
        monthlyRevenue: 39,
        joinedOn: '2026-03-07',
        email: 'elena@brooksfamilyphoto.com',
        phone: '+1 (555) 772-3399',
        publicUrl: 'ckam.io/elena-brooks',
        businessName: 'Brooks Family Photo',
        about: {
            en: 'Family photographer focused on weekday mini sessions and automated reminder flows.',
            ar: 'Family photographer focused on weekday mini sessions and automated reminder flows.',
        },
        preferredLanguage: 'English',
        preferredLanguageAr: 'English',
        preferredCurrency: 'USD',
        totalClients: 11,
        upcomingBookings: 3,
        experience: '4 years',
        experienceAr: '4 years',
        kycSubmitted: true,
    },
];

export const initialPlans = [
    {
        id: 'starter',
        name: { en: 'Starter', ar: 'البداية' },
        price: 39,
        billingCycle: 'monthly',
        billingLabel: { en: 'Billed monthly', ar: 'فوترة شهرية' },
        trialDays: 14,
        activeSubscribers: 14,
        status: 'published',
        description: {
            en: 'Portfolio basics for solo photographers starting with Tap.',
            ar: 'أساسيات البورتفوليو للمصورين الأفراد الذين يبدأون مع Tap.',
        },
        features: {
            en: ['1 team seat', 'Basic Tap onboarding', 'Client lead capture'],
            ar: ['مقعد فريق واحد', 'تهيئة Tap الأساسية', 'التقاط العملاء المحتملين'],
        },
    },
    {
        id: 'growth',
        name: { en: 'Growth', ar: 'النمو' },
        price: 129,
        billingCycle: 'monthly',
        billingLabel: { en: 'Billed monthly', ar: 'فوترة شهرية' },
        trialDays: 21,
        activeSubscribers: 8,
        status: 'published',
        description: {
            en: 'For growing studios that need automation and follow-up workflows.',
            ar: 'للاستوديوهات المتنامية التي تحتاج الأتمتة وتدفقات المتابعة.',
        },
        features: {
            en: ['3 team seats', 'Advanced Tap setup', 'Automated reminders'],
            ar: ['3 مقاعد فريق', 'إعداد Tap متقدم', 'تذكيرات آلية'],
        },
    },
    {
        id: 'studio-pro',
        name: { en: 'Studio Pro', ar: 'استوديو برو' },
        price: 349,
        billingCycle: 'annual',
        billingLabel: { en: 'Billed yearly', ar: 'فوترة سنوية' },
        trialDays: 30,
        activeSubscribers: 4,
        status: 'published',
        description: {
            en: 'Premium support, multi-location controls, and VIP onboarding.',
            ar: 'دعم مميز، تحكم متعدد المواقع، وتهيئة VIP.',
        },
        features: {
            en: ['Unlimited seats', 'Priority Tap support', 'Revenue reporting'],
            ar: ['مقاعد غير محدودة', 'دعم Tap بأولوية', 'تقارير الإيرادات'],
        },
    },
];

export const initialPromoCodes = [
    {
        id: 'promo-welcome',
        code: 'WELCOME10',
        type: 'percent',
        value: 10,
        appliesTo: ['all'],
        startsOn: '2026-04-01',
        endsOn: '2026-06-30',
        usageLimit: 200,
        usedCount: 37,
        status: 'active',
        description: {
            en: 'Welcome offer for first-time subscriptions.',
            ar: 'عرض ترحيبي للاشتراكات الجديدة لأول مرة.',
        },
    },
    {
        id: 'promo-growth50',
        code: 'GROWTH50',
        type: 'fixed',
        value: 50,
        appliesTo: ['growth', 'studio-pro'],
        startsOn: '2026-04-15',
        endsOn: '2026-07-31',
        usageLimit: 80,
        usedCount: 11,
        status: 'draft',
        description: {
            en: 'Fixed discount for growth-focused studios.',
            ar: 'خصم ثابت للاستوديوهات التي تركز على النمو.',
        },
    },
];

export const initialContentSections = [
    {
        id: 'home',
        name: { en: 'Home Page', ar: 'Home Page' },
        pagePath: '/',
        theme: 'warm-sand',
        status: 'live',
        eyebrow: {
            en: 'For photographer businesses',
            ar: 'For photographer businesses',
        },
        headline: {
            en: 'Book the right photographer faster with CKAM.',
            ar: 'Book the right photographer faster with CKAM.',
        },
        subheadline: {
            en: 'Showcase vetted creatives, automate lead capture, and move waitlist users into active subscriptions.',
            ar: 'Showcase vetted creatives, automate lead capture, and move waitlist users into active subscriptions.',
        },
        body: {
            en: 'The home page positions CKAM as the operator-facing hub for photographer discovery, onboarding, and subscription conversion.',
            ar: 'The home page positions CKAM as the operator-facing hub for photographer discovery, onboarding, and subscription conversion.',
        },
        highlights: {
            en: [
                'Bilingual public website experience',
                'Tap marketplace onboarding flow',
                'Waitlist capture that feeds admin review',
            ],
            ar: [
                'Bilingual public website experience',
                'Tap marketplace onboarding flow',
                'Waitlist capture that feeds admin review',
            ],
        },
        ctaLabel: {
            en: 'Join the waitlist',
            ar: 'Join the waitlist',
        },
        ctaLink: '/waitlist',
        secondaryCtaLabel: {
            en: 'View pricing',
            ar: 'View pricing',
        },
        secondaryCtaLink: '/pricing',
        seoTitle: {
            en: 'CKAM | Photographer platform and admin operations',
            ar: 'CKAM | Photographer platform and admin operations',
        },
        seoDescription: {
            en: 'Launch a bilingual photographer marketplace with onboarding, pricing, and lead capture managed from CKAM.',
            ar: 'Launch a bilingual photographer marketplace with onboarding, pricing, and lead capture managed from CKAM.',
        },
        modules: ['hero', 'trust-bar', 'feature-grid', 'waitlist-strip'],
        updatedAt: '2026-03-22',
    },
    {
        id: 'features',
        name: { en: 'Features Page', ar: 'Features Page' },
        pagePath: '/features',
        theme: 'editorial-night',
        status: 'draft',
        eyebrow: {
            en: 'Platform capabilities',
            ar: 'Platform capabilities',
        },
        headline: {
            en: 'Everything your photographer network needs to launch confidently.',
            ar: 'Everything your photographer network needs to launch confidently.',
        },
        subheadline: {
            en: 'Highlight Tap onboarding, revenue visibility, studio workflows, and fast approvals.',
            ar: 'Highlight Tap onboarding, revenue visibility, studio workflows, and fast approvals.',
        },
        body: {
            en: 'Use this page to break down the value of the dashboard, onboarding checkpoints, and customer lifecycle tools.',
            ar: 'Use this page to break down the value of the dashboard, onboarding checkpoints, and customer lifecycle tools.',
        },
        highlights: {
            en: [
                'Role-based dashboards for admin and photographers',
                'Tap onboarding checkpoints and payment readiness',
                'Calendar, booking, and subscription operations',
            ],
            ar: [
                'Role-based dashboards for admin and photographers',
                'Tap onboarding checkpoints and payment readiness',
                'Calendar, booking, and subscription operations',
            ],
        },
        ctaLabel: {
            en: 'Explore features',
            ar: 'Explore features',
        },
        ctaLink: '/features',
        secondaryCtaLabel: {
            en: 'Talk to sales',
            ar: 'Talk to sales',
        },
        secondaryCtaLink: '/contact',
        seoTitle: {
            en: 'CKAM Features | Photographer tools and business operations',
            ar: 'CKAM Features | Photographer tools and business operations',
        },
        seoDescription: {
            en: 'Present photographer workflows, onboarding controls, and customer management tools in a structured marketing layout.',
            ar: 'Present photographer workflows, onboarding controls, and customer management tools in a structured marketing layout.',
        },
        modules: ['hero', 'feature-grid', 'stats-band', 'faq-strip'],
        updatedAt: '2026-03-19',
    },
    {
        id: 'pricing',
        name: { en: 'Pricing Page', ar: 'Pricing Page' },
        pagePath: '/pricing',
        theme: 'premium-pricing',
        status: 'live',
        eyebrow: {
            en: 'Plans and billing',
            ar: 'Plans and billing',
        },
        headline: {
            en: 'Flexible plans for solo photographers and growing studios.',
            ar: 'Flexible plans for solo photographers and growing studios.',
        },
        subheadline: {
            en: 'Define monthly, annual, or custom billing cycles without leaving the admin panel.',
            ar: 'Define monthly, annual, or custom billing cycles without leaving the admin panel.',
        },
        body: {
            en: 'Keep pricing current, surface plan comparisons, and align website messaging with live subscription offers.',
            ar: 'Keep pricing current, surface plan comparisons, and align website messaging with live subscription offers.',
        },
        highlights: {
            en: [
                'Monthly and annual billing support',
                'Bilingual plan descriptions and features',
                'Clear CTA paths for self-serve and assisted sales',
            ],
            ar: [
                'Monthly and annual billing support',
                'Bilingual plan descriptions and features',
                'Clear CTA paths for self-serve and assisted sales',
            ],
        },
        ctaLabel: {
            en: 'View pricing',
            ar: 'View pricing',
        },
        ctaLink: '/pricing',
        secondaryCtaLabel: {
            en: 'Compare plans',
            ar: 'Compare plans',
        },
        secondaryCtaLink: '/features',
        seoTitle: {
            en: 'CKAM Pricing | Subscription plans for photographers',
            ar: 'CKAM Pricing | Subscription plans for photographers',
        },
        seoDescription: {
            en: 'Keep the public pricing page synchronized with live subscription plans, billing cycles, and lead capture flows.',
            ar: 'Keep the public pricing page synchronized with live subscription plans, billing cycles, and lead capture flows.',
        },
        modules: ['hero', 'pricing-grid', 'comparison-strip', 'faq-strip'],
        updatedAt: '2026-03-23',
    },
    {
        id: 'about',
        name: { en: 'About Page', ar: 'About Page' },
        pagePath: '/about',
        theme: 'minimal-studio',
        status: 'live',
        eyebrow: {
            en: 'Who we are',
            ar: 'Who we are',
        },
        headline: {
            en: 'CKAM is building the operational layer behind photographer growth.',
            ar: 'CKAM is building the operational layer behind photographer growth.',
        },
        subheadline: {
            en: 'Use this page to explain the product vision, operator mindset, and the value of a unified photographer ecosystem.',
            ar: 'Use this page to explain the product vision, operator mindset, and the value of a unified photographer ecosystem.',
        },
        body: {
            en: 'The About page can carry the brand story, marketplace trust signals, and the reasons photographers and studios choose CKAM.',
            ar: 'The About page can carry the brand story, marketplace trust signals, and the reasons photographers and studios choose CKAM.',
        },
        highlights: {
            en: [
                'Built for operators, not just portfolios',
                'Multi-language and multi-currency ready',
                'Designed for onboarding, conversion, and retention',
            ],
            ar: [
                'Built for operators, not just portfolios',
                'Multi-language and multi-currency ready',
                'Designed for onboarding, conversion, and retention',
            ],
        },
        ctaLabel: {
            en: 'Meet the platform',
            ar: 'Meet the platform',
        },
        ctaLink: '/about',
        secondaryCtaLabel: {
            en: 'Contact the team',
            ar: 'Contact the team',
        },
        secondaryCtaLink: '/contact',
        seoTitle: {
            en: 'About CKAM | Photographer growth and operations platform',
            ar: 'About CKAM | Photographer growth and operations platform',
        },
        seoDescription: {
            en: 'Tell the CKAM story, explain the product mission, and build trust before visitors move into plans or waitlists.',
            ar: 'Tell the CKAM story, explain the product mission, and build trust before visitors move into plans or waitlists.',
        },
        modules: ['hero', 'story-block', 'stats-band', 'cta-panel'],
        updatedAt: '2026-03-20',
    },
    {
        id: 'contact',
        name: { en: 'Contact Page', ar: 'Contact Page' },
        pagePath: '/contact',
        theme: 'contact-warm',
        status: 'live',
        eyebrow: {
            en: 'Contact and support',
            ar: 'Contact and support',
        },
        headline: {
            en: 'Reach the CKAM team for onboarding, support, and partnership requests.',
            ar: 'Reach the CKAM team for onboarding, support, and partnership requests.',
        },
        subheadline: {
            en: 'Give prospects a direct path to sales or support while keeping waitlist interest organized.',
            ar: 'Give prospects a direct path to sales or support while keeping waitlist interest organized.',
        },
        body: {
            en: 'Use the contact page to funnel inbound questions to the right team and track who needs follow-up.',
            ar: 'Use the contact page to funnel inbound questions to the right team and track who needs follow-up.',
        },
        highlights: {
            en: [
                'Direct contact path for sales and onboarding',
                'Support email and phone visibility',
                'Waitlist and contact flows tracked in admin',
            ],
            ar: [
                'Direct contact path for sales and onboarding',
                'Support email and phone visibility',
                'Waitlist and contact flows tracked in admin',
            ],
        },
        ctaLabel: {
            en: 'Contact us',
            ar: 'Contact us',
        },
        ctaLink: '/contact',
        secondaryCtaLabel: {
            en: 'Join the waitlist',
            ar: 'Join the waitlist',
        },
        secondaryCtaLink: '/waitlist',
        seoTitle: {
            en: 'Contact CKAM | Support and photographer onboarding',
            ar: 'Contact CKAM | Support and photographer onboarding',
        },
        seoDescription: {
            en: 'Route support, onboarding, and partnership inquiries through a clean public contact page connected to admin follow-up.',
            ar: 'Route support, onboarding, and partnership inquiries through a clean public contact page connected to admin follow-up.',
        },
        modules: ['hero', 'contact-form', 'faq-strip', 'waitlist-strip'],
        updatedAt: '2026-03-24',
    },
];

export const initialBrandSettings = {
    logoText: { en: 'CKAM', ar: 'CKAM' },
    logoUrl: 'https://dummyimage.com/160x48/132238/ffffff&text=CKAM',
    headerAnnouncement: {
        en: 'New studio partnerships are now open for spring onboarding.',
        ar: 'New studio partnerships are now open for spring onboarding.',
    },
    headerCtaLabel: {
        en: 'Book a demo',
        ar: 'Book a demo',
    },
    footerSummary: {
        en: 'CKAM helps photographer businesses launch, convert, and scale with operational clarity.',
        ar: 'CKAM helps photographer businesses launch, convert, and scale with operational clarity.',
    },
    footerCtaLabel: {
        en: 'Talk to CKAM',
        ar: 'Talk to CKAM',
    },
    footerCtaLink: '/contact',
    supportEmail: 'support@ckam.io',
    contactNumber: '+1 (555) 240-9080',
    waitingListHeadline: {
        en: 'Join the photographer waitlist',
        ar: 'Join the photographer waitlist',
    },
};
export const initialWaitlist = [
    {
        id: 'w-201',
        name: 'Harper West',
        email: 'harper@studioflow.co',
        interest: 'Wedding leads',
        source: 'Home page form',
        status: 'new',
        requestedAt: '2026-03-11',
        notes: 'Asked for a studio demo.',
    },
    {
        id: 'w-202',
        name: 'Mason Lee',
        email: 'mason@pixelforge.co',
        interest: 'Tap onboarding',
        source: 'Pricing page',
        status: 'reviewed',
        requestedAt: '2026-03-10',
        notes: 'Comparing monthly vs annual billing.',
    },
    {
        id: 'w-203',
        name: 'Isla Freeman',
        email: 'isla@lumenworks.io',
        interest: 'Subscription upgrade',
        source: 'Contact page',
        status: 'contacted',
        requestedAt: '2026-03-08',
        notes: 'Requested migration support.',
    },
    {
        id: 'w-204',
        name: 'Luca Chen',
        email: 'luca@northframe.com',
        interest: 'Portrait workflows',
        source: 'Features page',
        status: 'new',
        requestedAt: '2026-03-13',
        notes: 'Interested in automation examples.',
    },
    {
        id: 'w-205',
        name: 'Amara Scott',
        email: 'amara@focuslane.co',
        interest: 'Enterprise onboarding',
        source: 'Referral',
        status: 'reviewed',
        requestedAt: '2026-03-09',
        notes: 'Needs multi-location support.',
    },
];

export const initialContactMessages = [
    {
        id: 'msg-301',
        name: 'Olivia Parker',
        email: 'olivia@northlight.studio',
        subject: 'Partnership inquiry',
        message: 'Hi team, we want to discuss a partnership plan for two studio branches.',
        status: 'new',
        source: 'Public contact form',
        locale: 'en',
        createdAt: '2026-03-25T10:45:00.000Z',
    },
    {
        id: 'msg-302',
        name: 'سارة أحمد',
        email: 'sarah@alnour.photo',
        subject: 'استفسار عن التهيئة',
        message: 'مرحباً، أحتاج مساعدة في تهيئة الحساب وربط المدفوعات.',
        status: 'reviewed',
        source: 'Public contact form',
        locale: 'ar',
        createdAt: '2026-03-26T08:10:00.000Z',
    },
];

export const initialBlogPosts = [
    {
        id: 'blog-001',
        slug: 'how-top-studios-turn-inquiries-into-confirmed-bookings',
        title: {
            en: 'How top studios turn inquiries into confirmed bookings',
            ar: 'كيف تحوّل الاستوديوهات الرائدة الاستفسارات إلى حجوزات مؤكدة',
        },
        excerpt: {
            en: 'A practical playbook for moving clients from first interest to a paid, scheduled session.',
            ar: 'دليل عملي لنقل العميل من الاهتمام الأول إلى جلسة مدفوعة ومجدولة.',
        },
        content: {
            en: 'A great booking experience is not only about having a form. It is about giving the client confidence, clarity, and a simple next step.',
            ar: 'تجربة الحجز الممتازة لا تعتمد فقط على وجود نموذج، بل على منح العميل الثقة والوضوح وخطوة تالية بسيطة.',
        },
        category: 'Booking Strategy',
        author: 'C-KAM Editorial',
        readTime: '8 min read',
        status: 'published',
        featured: true,
        imageUrl: '/assets/img/blog/blog-1.jpg',
        publishedAt: '2026-04-20',
    },
    {
        id: 'blog-002',
        slug: 'design-a-premium-client-journey-from-first-message-to-delivery',
        title: {
            en: 'Design a premium client journey from first message to delivery',
            ar: 'صمّم رحلة عميل مميزة من أول رسالة حتى التسليم',
        },
        excerpt: {
            en: 'Use intentional steps to build trust and make every client interaction feel polished.',
            ar: 'استخدم خطوات مقصودة لبناء الثقة وجعل كل تفاعل مع العميل أكثر احترافية.',
        },
        content: {
            en: 'Premium experience comes from consistency: clear communication, fast confirmation, and thoughtful delivery moments.',
            ar: 'التجربة المميزة تأتي من الاتساق: تواصل واضح، تأكيد سريع، ولحظات تسليم مدروسة.',
        },
        category: 'Client Experience',
        author: 'C-KAM Editorial',
        readTime: '7 min read',
        status: 'draft',
        featured: false,
        imageUrl: '/assets/img/blog/blog-2.jpg',
        publishedAt: '2026-04-18',
    },
];





